%%{init: {"theme":"neutral","flowchart":{"curve":"basis","htmlLabels":true}}}%%
flowchart LR
    classDef ref  fill:#E8F0E8,stroke:#1F4E79,color:#1F4E79
    classDef fact fill:#FFE7CE,stroke:#C8702A,stroke-width:2px,color:#C8702A

    GEO["<b>Géographie</b><br/>continent · country · region · city"]:::ref
    ORG["<b>Organisation RH</b><br/>org_country · org_company · org_department<br/>org_section · org_group · employee"]:::ref
    PRD["<b>Produits &amp; Fournisseurs</b><br/>product_line · category · group · product<br/>price_history · discount · supplier"]:::ref
    CUS["<b>Clients</b><br/>customer_group · customer · loyalty_card"]:::ref
    ORD["<b>Commandes (transactionnel)</b><br/>sales_order · sales_order_line · sales_channel"]:::fact

    GEO --> CUS
    GEO --> ORG
    CUS --> ORD
    PRD --> ORD
    ORG --> ORD
