%%{init: {"theme":"neutral","flowchart":{"curve":"basis"}}}%%
flowchart TD
    classDef init  fill:#1F4E79,stroke:#1F4E79,color:#FFF
    classDef stop  fill:#000,stroke:#000,color:#FFF
    classDef act   fill:#E8F0E8,stroke:#1F4E79,color:#1F4E79
    classDef dec   fill:#FFF6D6,stroke:#C8702A,color:#5C3A0F
    classDef err   fill:#FBE5E5,stroke:#B22222,color:#7A1A1A

    S(( )):::init
    A1["Identifier le client<br/>(id ou création)"]:::act
    A2["Constituer le panier<br/>(produits et quantités)"]:::act
    A3["Calculer prix unitaire<br/>via historique_prix"]:::act
    A4["Appliquer remise active<br/>(remise_produit)"]:::act
    D1{"Stock disponible<br/>pour toutes les lignes ?"}:::dec
    A5["Refuser ou proposer<br/>article de remplacement"]:::err
    A6["Choisir canal de vente<br/>(MAGASIN / CATALOGUE / INTERNET)"]:::act
    A7["Affecter le commercial<br/>(employe_id)"]:::act
    A8["Insérer commande<br/>(BEGIN TX)"]:::act
    A9["Insérer N ligne_commande<br/>(grain ligne)"]:::act
    A10["Calculer montant_total<br/>= Σ montant_net"]:::act
    D2{"Client adhérent<br/>Orion Star Club ?"}:::dec
    A11["Créditer points<br/>fidélité"]:::act
    A12["COMMIT"]:::act
    A13["Émettre confirmation<br/>de commande"]:::act
    E(( )):::stop

    S --> A1 --> A2 --> A3 --> A4 --> D1
    D1 -- non --> A5 --> E
    D1 -- oui --> A6 --> A7 --> A8 --> A9 --> A10 --> D2
    D2 -- oui --> A11 --> A12
    D2 -- non --> A12
    A12 --> A13 --> E
