%%{init: {"theme":"neutral","flowchart":{"curve":"basis","htmlLabels":true,"nodeSpacing":40,"rankSpacing":50}}}%%
flowchart LR
    classDef comp   fill:#FFF8DC,stroke:#444,stroke-width:1.5px,color:#1F2A44,font-weight:bold
    classDef ms     fill:#CCE5FF,stroke:#1F4E79,stroke-width:1.5px,color:#1F2A44,font-weight:bold
    classDef pg     fill:#FFE7CE,stroke:#C8702A,stroke-width:1.5px,color:#5C3A0F,font-weight:bold
    classDef ui     fill:#F5E1FF,stroke:#7A3A9C,stroke-width:1.5px,color:#3A1A5C,font-weight:bold
    classDef ifc    fill:#FFF,stroke:#666,stroke-dasharray:3 3,color:#333

    %% Composants applicatifs
    DG["«component»<br/><b>data-gen</b><br/>Python · Faker"]:::comp
    ORC["«component»<br/><b>orchestrator</b><br/>Python · psycopg · pyodbc<br/>APScheduler"]:::comp
    PGA["«component»<br/><b>Adminer</b><br/>UI multi-SGBD<br/>(pgsql + mssql)"]:::ui

    %% Bases
    OLTP[("«database»<br/><b>orion_oltp</b><br/>Postgres · ops.*")]:::pg
    DWH[("«database»<br/><b>orion_dwh</b><br/>Postgres · dw.*")]:::pg
    MS[("«database»<br/><b>OrionETL</b><br/>SQL Server<br/>staging · etl · dim · fact")]:::ms

    %% Interfaces fournies
    I1>"«interface»<br/>SQL/JDBC ops.*"]:::ifc
    I2>"«interface»<br/>SQL/JDBC dw.*"]:::ifc
    I3>"«interface»<br/>TDS/sqlcmd<br/>etl.sp_*"]:::ifc
    I4>"«interface»<br/>HTTP :8080"]:::ifc

    OLTP --- I1
    DWH  --- I2
    MS   --- I3
    PGA  --- I4

    %% Liens (lollipop = fournit, dashed = utilise)
    DG  -. "uses (write)"          .-> I1
    ORC -. "uses (read)"           .-> I1
    ORC -. "uses (read+write+EXEC)" .-> I3
    ORC -. "uses (write)"          .-> I2
    PGA -. "uses (read/admin)"     .-> I1
    PGA -. "uses (read/admin)"     .-> I2
    PGA -. "uses (read/admin)"     .-> I3

    %% Configuration partagée
    subgraph CFG ["Configuration"]
      ENV["«artifact»<br/>.env<br/>credentials, cron, dates"]:::comp
    end
    ENV -. "lue par" .-> DG
    ENV -. "lue par" .-> ORC
    ENV -. "lue par" .-> MS
    ENV -. "lue par" .-> PGA

    %% Bibliothèques
    subgraph LIB ["Bibliothèques Python"]
      L1["psycopg"]:::comp
      L2["pyodbc"]:::comp
      L3["msodbcsql18"]:::comp
      L4["faker"]:::comp
      L5["apscheduler"]:::comp
    end
    DG  --> L4
    DG  --> L1
    ORC --> L1
    ORC --> L2
    ORC --> L3
    ORC --> L5
