%%{init: {"theme":"neutral","flowchart":{"curve":"basis","htmlLabels":true,"nodeSpacing":35,"rankSpacing":45}}}%%
flowchart TB
    classDef node   fill:#FFF,stroke:#1F4E79,stroke-width:2px,color:#1F2A44,font-weight:bold
    classDef ms     fill:#CCE5FF,stroke:#1F4E79,stroke-width:2px,color:#1F2A44,font-weight:bold
    classDef pg     fill:#FFE7CE,stroke:#C8702A,stroke-width:2px,color:#5C3A0F,font-weight:bold
    classDef art    fill:#E8F0E8,stroke:#1F4E79,color:#1F4E79
    classDef vol    fill:#FFFBE5,stroke:#B58900,color:#5C3A0F
    classDef net    fill:#F5F5F5,stroke:#666,stroke-dasharray:5 4,color:#333,font-weight:bold

    HOST["🖥 «device»<br/><b>Hôte Linux</b>"]:::node

    subgraph DOCKER ["«executionEnvironment» Docker Engine"]
      direction TB

      subgraph NET ["«network» orion-net"]
        direction LR

        N1["«node : container»<br/><b>postgres-oltp</b><br/>postgres:16<br/>:5433 → :5432"]:::pg
        N2["«node : container»<br/><b>postgres-dwh</b><br/>postgres:16<br/>:5434 → :5432"]:::pg
        N3["«node : container»<br/><b>mssql-etl</b><br/>mssql/server:2022<br/>+ unixODBC + psqlodbc<br/>:1433"]:::ms
        N4["«node : container»<br/><b>orchestrator</b><br/>python:3.12 + msodbcsql18"]:::node
        N5["«node : container»<br/><b>data-gen</b><br/>python:3.12<br/>profile=seed"]:::node
        N6["«node : container»<br/><b>adminer</b><br/>adminer:5<br/>:8080 → :8080"]:::node

        A1["📦 «artifact»<br/>oltp/init/*.sql"]:::art
        A2["📦 «artifact»<br/>dwh/init/*.sql"]:::art
        A3["📦 «artifact»<br/>mssql-etl/init/*.sql<br/>(7 scripts T-SQL)"]:::art
        A4["📦 «artifact»<br/>orchestrator/orchestrate.py"]:::art
        A5["📦 «artifact»<br/>data-gen/generate.py"]:::art
        A6["📦 «artifact»<br/>adminer/index.php<br/>(plugin login-servers)"]:::art

        V1[("💾 «volume»<br/>oltp_data")]:::vol
        V2[("💾 «volume»<br/>dwh_data")]:::vol
        V3[("💾 «volume»<br/>mssql_data")]:::vol

        A1 -.-> N1
        A2 -.-> N2
        A3 -.-> N3
        A4 -.-> N4
        A5 -.-> N5
        A6 -.-> N6

        N1 -.-> V1
        N2 -.-> V2
        N3 -.-> V3
      end
    end

    HOST --> DOCKER

    USR["👤 Utilisateur"]:::node
    USR -- "HTTP :8080"   --> N6
    USR -- "psql :5433"   --> N1
    USR -- "psql :5434"   --> N2
    USR -- "sqlcmd :1433" --> N3

    N5 -- "TDS"      --> N1
    N4 -- "TDS read" --> N1
    N4 -- "TDS r/w"  --> N3
    N4 -- "TDS write"--> N2
    N6 -. "TDS r/o"  .-> N1
    N6 -. "TDS r/o"  .-> N2
    N6 -. "TDS r/o"  .-> N3

    class NET net
    class DOCKER net
